schema:
  metadata:
    - name: sampleId
      type: string
      generateIndex: true
    - name: batchId
      type: string
      generateIndex: true
    - name: locationCode
      type: string
      generateIndex: true
    - name: samplingDate
      type: date
      generateIndex: false
    - name: locationName
      type: string
      generateIndex: true
    - name: readId
      type: string
    - name: sr2siloVersion
      type: string
      generateIndex: true
  opennessLevel: OPEN
  instanceName: wise-sarsCoV2
  features:
    - name: generalizedAdvancedQuery
  primaryKey: readId
siloClientThreadCount: 96
